name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main  # or your deployment branch
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/student-performance_prediction:latest

# Optional: Trigger Render deployment via webhook after Docker push
# Uncomment and update the URL if you use Render webhooks
#      - name: Trigger Render Deploy Hook
#        run: curl -X POST """ ${{ secrets.RENDER_DEPLOY_HOOK_URL }